IMR-160 feat: add db, dto related code
kCMI113/genie_crawler pull request #30
Opened 2023-08-09 10:50 UTC by kCMI113

## Overview
- 크롤러 레포에 db관련 코드를 추가합니다.
- [해당 레포](https://github.com/boostcampaitech5/level3_recsys_finalproject-recsys-03)의 디비 코드를 기반으로 한 후, 변경이 필요한 부분들을 수정하였습니다.

## Change Log
- 백엔드에 있던 코드를 기준으로 한 변경사항입니다.
- album docs 추가
- 크롤링 된 raw 데이터 기준으로 attribute 수정
- 날짜기준 쿼리 추가
- 코드 스타일 통일

## To Reviewer
- 대왕커밋이 되었습니다.. 반성하겠습니다..
- db관련 코드 작성이 처음이라 올바르게 한 게 맞는지 .. 걱정이 됩니다.. 꼼꼼하게 봐주시면 감사하겠습니다🥹
- pr이 너무 커질 것 같아 해당 pr 머지 후 테스트 코드 작성 예정입니다. 그러므로 아직 정상작동을 보장할 수 없다는 점 참고해주세요!

## Issue Tags
- [Jira issue](https://btcamplevel3.atlassian.net/browse/IMR-160?atlOrigin=eyJpIjoiNDg3MGYyODU4NmQxNGQ4OTk1ZDllNjMyNTcwODI2MzkiLCJwIjoiaiJ9)

2023-08-09 11:28 UTC, 2jun0 requested changes
수고 많으셨어요! 리뷰 확인해주세요!
테슷흐 코드도.. 핫핫

2023-08-09 11:28 UTC, 2jun0 commented on db/repository/album.py
> +    def create_Album(self, genie_id: str, name: str, img_url: str, released_date: date, created_at: datetime) -> Album:
생성할때 생성날짜를 받는건 좋지 않은 것 같아요

2023-08-09 11:28 UTC, 2jun0 commented on db/document/album.py
> +    updated_at = DateTimeField(required=True)
생성할때 자동으로 생성날짜를 지정해주는게 좋을 것 같아요  
자동 업데이트도 아래와 같이 하면 된다는 것 같아요 [참고](https://stackoverflow.com/questions/8098122/mongoengine-creation-time-attribute-in-document)  

```python
class User(Document):
    # other fields...
    created_at = DateTimeField(required=True, default=datetime.utcnow)
    updated_at = DateTimeField(required=True)

class Post(Document):
    # other fields...
    created_at = DateTimeField(required=True, default=datetime.utcnow)
    updated_at = DateTimeField(required=True)

def update_timestamp(sender, document, **kwargs):
    document.updated_at = datetime.utcnow()

signals.pre_save.connect(update_timestamp, sender=User)
signals.pre_save.connect(update_timestamp, sender=Post)
```

+ 몽고db는 날짜를 UTC(유니버셜 타임 뭐시기)로 표기한다고 해요! [참고1](https://www.mongodb.com/docs/v4.4/tutorial/model-time-data/#model-time-data) [참고2](https://nashorn.tistory.com/entry/MongoDB-%ED%83%80%EC%9E%84-%EC%A1%B4-%EA%B4%80%EB%A0%A8-%EC%9D%B4%EC%8A%88)

2023-08-09 11:28 UTC, 2jun0 commented on db/document/inference.py
> +    updated_at = DateTimeField(required=True)
`EmbeddedDocument`는 실제 document가 아니예요 그냥 아래와 같이 하고 싶어서 그래요  
코드가 좀 복잡하긴 해요? 이부분은 수정할까 고민도 됩니다. (대안으로 LikeDoc 추가..?)
```
{
  id: 1231233
  emb: {
    # nest dict 하고 싶었음!
  }
}
```

2023-08-09 11:28 UTC, 2jun0 commented on db/document/inference.py
이 doc는 지니 크롤러에서 필요 없는것 같아요

2023-08-09 11:28 UTC, 2jun0 commented on db/document/user.py
이 doc는 지니 크롤러에서 필요 없는것 같아요

2023-08-09 11:28 UTC, 2jun0 commented on db/document/user.py
> +    fingerprint = StringField(required=True, unique=True)
이건 좀 딴소린데, 이 필드 삭제할겁니다!

2023-08-09 11:28 UTC, 2jun0 commented on db/exception/inference.py
이 예외는 지니 크롤러에서 필요 없는것 같아요

2023-08-09 11:28 UTC, 2jun0 commented on db/exception/user.py
이 예외는 지니 크롤러에서 필요 없는것 같아요

2023-08-09 11:28 UTC, 2jun0 commented on db/repository/album.py
> +        Album = AlbumDocument(
수정해주세요
```suggestion
        album = AlbumDocument(
```

2023-08-09 11:28 UTC, 2jun0 commented on db/repository/album.py
> +        Album = AlbumDocument(
아래도 마찬가지!

2023-08-09 11:28 UTC, 2jun0 commented on db/repository/inference.py
이 레포는 지니 크롤러에서 필요 없는것 같아요

2023-08-09 11:28 UTC, 2jun0 commented on db/repository/user.py
이 레포는 지니 크롤러에서 필요 없는것 같아요

2023-08-09 11:28 UTC, 2jun0 commented on dto/model/inference.py
이 dto는 지니 크롤러에서 필요 없는것 같아요

2023-08-09 11:28 UTC, 2jun0 commented on dto/model/user.py
이 dto는 지니 크롤러에서 필요 없는것 같아요

2023-08-10 05:24 UTC, 2jun0 requested changes
수고하셨어요! 마지막으로 한번만 더 부탁드릴게요!

2023-08-10 05:24 UTC, 2jun0 commented on db/repository/album.py
> +        album: AlbumDocument = AlbumDocument.objects(genie_id=genie_id)
타입을 QuerySet[AlbumDocument]로 바꿔주세요!

2023-08-10 05:24 UTC, 2jun0 commented on db/repository/album.py
> +        album: AlbumDocument = AlbumDocument.objects(genie_id=genie_id)
```suggestion
        album: QuerySet[AlbumDocument] = AlbumDocument.objects(genie_id=genie_id)
```

2023-08-10 05:24 UTC, 2jun0 commented on db/repository/artist.py
> +        artist: ArtistDocument = ArtistDocument.objects(genie_id=genie_id)
```suggestion
        artist: QuerySet[ArtistDocument] = ArtistDocument.objects(genie_id=genie_id)
```

2023-08-10 05:24 UTC, 2jun0 commented on db/repository/playlist.py
> +        playlist: PlaylistDocument = PlaylistDocument.objects(genie_id=genie_id)
```suggestion
        playlist: QuerySet[PlaylistDocument] = PlaylistDocument.objects(genie_id=genie_id)
```

2023-08-10 05:24 UTC, 2jun0 commented on db/repository/song.py
> +        query_set = SongDocument.objects(genie_id=genie_id)
```suggestion
        query_set: QuerySet[SongDocument] = SongDocument.objects(genie_id=genie_id)
```

2023-08-10 05:51 UTC, kCMI113 commented on db/repository/album.py
> +        album: AlbumDocument = AlbumDocument.objects(genie_id=genie_id)
해당 변경사항은 논의한 방향으로 변경하도록 하겠습니당!

2023-08-10 06:16 UTC, 2jun0 approved these changes
이거지이 LGTM!

2023-08-10 06:16 UTC, merged