IMR-163 feat: add test for db repo
kCMI113/genie_crawler pull request #31
Opened 2023-08-11 12:22 UTC by kCMI113

## Overview
- db 테스트 코드를 추가합니다.
- 더불어 앞선 피알에서 잡아내지 못했던 잘못된 코드들을 수정하였습니다.

## Change Log
- infer, user 흔적 삭제 및 경로, 변수 등 소소한 수정
- mongo db와 python간 시간 기준 차이가 있어 이를 수정하기 위해 date.py mixin 추가
- 4개의 test 추가

## To Reviewer
- test 모두 문제없이 동작함을 확인하였습니다!

## Issue Tags
- [Jira issue](https://btcamplevel3.atlassian.net/browse/IMR-163?atlOrigin=eyJpIjoiMzUyOGJmNzg1OTBiNGFkNTkzNDI2MTkzN2FkOTY5NzYiLCJwIjoiaiJ9)

2023-08-11 15:31 UTC, 2jun0 requested changes
수고하셨어욤~

2023-08-11 15:31 UTC, 2jun0 commented on db/document/album.py
> +class AlbumDocument(CreatedAtMixin, UpdatedAtMixin, Document):
상속은 오른쪽에서 왼쪽으로 된다고 해요! 
다들 Document에 의존하는 친구들이니 Document를 가장 오른쪽으로 두는게 좋은것 같아요! 👍

2023-08-11 15:31 UTC, 2jun0 commented on db/repository/album.py
오타가 있었군요? 하하

2023-08-11 15:31 UTC, 2jun0 commented on tests/db/repository/test_album.py
> +    albumRepository = AlbumRepository()
camel_case로 해주세염~
```suggestion
    album_repository = AlbumRepository()
```

2023-08-12 01:41 UTC, kCMI113 commented on db/document/mixin/date.py
> +signals.pre_save.connect(update_updated_at, sender=UpdatedAtMixin)
반올림시 아래와 같은 경우 오류가 발생합니다. 버림을 하는게 더 적합할 것 같습니다.

dt = datetime.datetime(2023, 8, 12, 1, 34, 2, 999754)

    def round_millisecond(dt: datetime):
>       return dt.replace(microsecond=round(dt.microsecond, -3))
E       ValueError: microsecond must be in 0..999999

2023-08-12 02:55 UTC, 2jun0 approved these changes
LGTM!

2023-08-12 02:55 UTC, merged