IMR-157 feat: add csv to db migration
kCMI113/genie_crawler pull request #32
Opened 2023-08-13 06:01 UTC by kCMI113

## Overview
- 이전에 크롤링해 csv 형태로 저장된 데이터를 db로 이동합니다.

## Change Log
### migration
- csv기준으로 노래/플리로 파일을 나누었습니다.
- 데이터가 서로 의존하고 있어 앨범 -> 아티스트 -> 노래 -> 플리 순으로 디비에 넣습니다
- migration.py를 통해 이동이 진행됩니다.
### spotify
- 스포티파이 url을 가져와야해 이와 관련된 코드를 추가합니다.
### config
- pydantic을 통해 config를 관리합니다.

## To Reviewer
### 23.8.13
- 현재 곡만 완성되었으며, 앨범, 아티스트, 노래는 디비에 잘 들어가는 것을 확인하였습니다.
- 플레이리스트도 현재 완성된 SongCsvMigrate와 비슷한 형태로 작성될 것입니다.
- 원활한 PlaylistCsvMigrate 테스트를 위해 곡, 앨범, 아티스트를 이동한 후에 마저 작성하려 합니다. 그러니 머지하지 말고 리뷰만 해주세요!

## Issue Tags
- [Jira issue](https://btcamplevel3.atlassian.net/browse/IMR-157?atlOrigin=eyJpIjoiZTkxZmQzZDc2OGY5NDg3YmFlYzk4YWI5M2EwZjU2NzIiLCJwIjoiaiJ9)

2023-08-13 06:22 UTC, 2jun0 requested changes
get_spotify_url함수 라인이 너무 길어서  flake8이 오류를 발생시켜요 ㅠㅠ

2023-08-13 06:22 UTC, 2jun0 commented on migration.py
> +SONG_PATH = os.path.join(INPUT_PATH, "join_songs_0726.csv")
이 변수들의 값은 변경될 수 있으니
설정에 들어가면 좋을것 같아요

2023-08-13 06:22 UTC, 2jun0 commented on spotify/spotify.py
> +    secret = config.spotify_pwd
설정부분은 전역으로 빼도 괜찮을 것 같은데 어떤가요?

2023-08-13 06:22 UTC, 2jun0 commented on spotify/spotify.py
> +    seary_query = title + " " + artist
```suggestion
    search_query = title + " " + artist
```

2023-08-13 06:22 UTC, 2jun0 commented on spotify/spotify.py
> +    sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager, language="ko")
Spotify객체는 이 함수에서 받는 인자들과 상관없이 항상 같은 동작을 하는 것 같습니다.
두가지 방법을 제안해봅니다
1. Spotify객체를 외부에서 생성하고, get_spotify_url의 인자로 받기
2. Spotify객체 생성을 __init__에서 하고, get_spotify_url메서드를 가지는 SpotifyManager 클래스 생성

2023-08-13 06:22 UTC, 2jun0 commented on spotify/spotify.py
> +    for item in result["tracks"]["items"]:
`result`값 그대로 사용하는 부분은 없고, 뒤에 항상 `["tracks"]`이 따라오므로 편의를 위해 아래와 같이 tracks변수를 할당하는건 어떤가요?
```
tracks = result["tracks"]
...
for item in tracks["items"]:
```

2023-08-13 06:24 UTC, kCMI113 commented on migration.py
> +SONG_PATH = os.path.join(INPUT_PATH, "join_songs_0726.csv")
config에 넣자는 말씀이신가요?

2023-08-13 06:25 UTC, 2jun0 commented on migration.py
> +SONG_PATH = os.path.join(INPUT_PATH, "join_songs_0726.csv")
네!

2023-08-13 06:27 UTC, kCMI113 commented on spotify/spotify.py
> +    for item in result["tracks"]["items"]:
그렇게 했을 때 어떤 이점이 있을지 설명해주실 수 있을까요? 제가 생각한 바로는 별다른 차이는 없을 것 같아서요..~

2023-08-13 06:29 UTC, kCMI113 commented on spotify/spotify.py
> +    sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager, language="ko")
back의 get_logger와 같은 느낌으로 전역으로 쓰는 것은 어떨까요?

2023-08-15 14:42 UTC, 2jun0 approved these changes
LGTM

2023-08-15 14:42 UTC, merged